#!/bin/sh

# === Plugins ===
# (cat ~/.cache/wal/sequences &)
eval "$(zoxide init zsh)"
eval "$(starship init zsh)"
eval "$(direnv hook zsh)"
source "/opt/homebrew/opt/fzf/shell/completion.zsh" 2> /dev/null
source "/opt/homebrew/opt/fzf/shell/key-bindings.zsh" 2> /dev/null
source "/opt/homebrew/share/zsh-autosuggestions/zsh-autosuggestions.zsh" 2> /dev/null

export "ZSH_HIGHLIGHT_HIGHLIGHTERS_DIR=/opt/homebrew/share/zsh-syntax-highlighting/highlighters" 2> /dev/null
source "/opt/homebrew/share/zsh-syntax-highlighting/zsh-syntax-highlighting.zsh" 2> /dev/null
